bon_plan:
    resource: "@BonPlanBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb
ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"