<?php

namespace BonPlanBundle\Repository;

/**
 * VoitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonPlanRepository extends \Doctrine\ORM\EntityRepository
{

    public function getBonPlanDisponible($adresse)
    {
        $query=$this->getEntityManager()->createQuery("SELECT bp FROM BonPlanBundle:BonPlan bp WHERE bp.adresse=:adresse and bp.nbreCoupon>0")
        ->setParameter('adresse',$adresse);

        return $query->getResult();

    }

    public function getBonPlan()
    {
        $query=$this->getEntityManager()->createQuery("SELECT bp FROM BonPlanBundle:BonPlan bp WHERE  bp.nbreCoupon>0");
        return $query->getResult();

    }
}
