<?php

namespace BonPlanBundle\Repository;

/**
 * UtilisatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisatRepository extends \Doctrine\ORM\EntityRepository
{
    public function ajpi(){

    }

    public function findByRole($role)
    {
            $query = $this->getEntityManager()->createQuery("SELECT u From BonPlanBundle:Utilisateur u WHERE u.role=:role ORDER BY u.nbPoints DESC ")
                ->setParameter('role', $role);

        return $query->getResult();

    }

    public function getRecipientValue()
    {
        $query=$this->getEntityManager()->createQuery("select u from BonPlanBundle:Utilisateur u WHERE u.role='Bon Planeur' ORDER BY u.nbPoints DESC");

        return $query->getResult();

    }

    public function updateRewardValue($i)
    {
        $query=$this->getEntityManager()->createQuery("UPDATE BonPlanBundle:Utilisateur u SET u.rewarded=:i WHERE u.role='Bon Planeur'")
            ->setParameter('i',$i);
        $query->execute();
    }

    public function InitializePoints()
    {
        $query=$this->getEntityManager()->createQuery("UPDATE BonPlanBundle:Utilisateur u SET u.nbPoints=0 WHERE u.role='Bon Planeur'");
        $query->execute();

    }

}
