user_index:
    path:     /
    defaults: { _controller: "BonPlanBundle:Utilisateur:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "BonPlanBundle:Utilisateur:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "BonPlanBundle:Utilisateur:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "BonPlanBundle:Utilisateur:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "BonPlanBundle:Utilisateur:delete" }
    methods:  DELETE
